server:
  name: orders
  version: 2.1.1
  jwt_key: testKey
  http:
    addr: 0.0.0.0:4466
    timeout: 1s
  grpc:
    addr: 0.0.0.0:6677
    timeout: 1s
  jaeger_url: http://localhost:14268/api/traces
data:
  database:
    driver: mysql
    source: root:uUiknmbGFDBIu9801827654@tcp(127.0.0.1:3307)/ghost
    set_max_idle_conns: 50
    set_max_open_conns: 100
    set_conn_max_lifetime: 3600s
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
